export const latexSymbols = [
    {
        category: "Huruf Yunani",
        symbols: [
            { latex: "\\alpha ", description: "(alpha)" },
            { latex: "\\beta ", description: "(beta)" },
            { latex: "\\gamma ", description: "(gamma)" },
            { latex: "\\Gamma ", description: "(Gamma)" },
            { latex: "\\delta ", description: "(delta)" },
            { latex: "\\Delta ", description: "(Delta)" },
            { latex: "\\epsilon ", description: "(epsilon)" },
            { latex: "\\varepsilon ", description: "(varepsilon)" },
            { latex: "\\zeta ", description: "(zeta)" },
            { latex: "\\eta ", description: "(eta)" },
            { latex: "\\theta ", description: "(theta)" },
            { latex: "\\vartheta ", description: "(vartheta)" },
            { latex: "\\Theta ", description: "(Theta)" },
            { latex: "\\iota ", description: "(iota)" },
            { latex: "\\kappa ", description: "(kappa)" },
            { latex: "\\lambda ", description: "(lambda)" },
            { latex: "\\Lambda ", description: "(Lambda)" },
            { latex: "\\mu ", description: "(mu)" },
            { latex: "\\nu ", description: "(nu)" },
            { latex: "\\xi ", description: "(xi)" },
            { latex: "\\Xi ", description: "(Xi)" },
            { latex: "\\pi ", description: "(pi)" },
            { latex: "\\Pi ", description: "(Pi)" },
            { latex: "\\rho ", description: "(rho)" },
            { latex: "\\varrho ", description: "(varrho)" },
            { latex: "\\sigma ", description: "(sigma)" },
            { latex: "\\Sigma ", description: "(Sigma)" },
            { latex: "\\tau ", description: "(tau)" },
            { latex: "\\upsilon ", description: "(upsilon)" },
            { latex: "\\Upsilon ", description: "(Upsilon)" },
            { latex: "\\phi ", description: "(phi)" },
            { latex: "\\varphi ", description: "(varphi)" },
            { latex: "\\Phi ", description: "(Phi)" },
            { latex: "\\chi ", description: "(chi)" },
            { latex: "\\psi ", description: "(psi)" },
            { latex: "\\Psi ", description: "(Psi)" },
            { latex: "\\omega ", description: "(omega)" },
            { latex: "\\Omega ", description: "(Omega)" },
        ],
    },
    {
        category: "Panah",
        symbols: [
            { latex: "\\leftarrow ", description: "" },
            { latex: "\\rightarrow ", description: "" },
            { latex: "\\leftrightarrow ", description: "" },
            { latex: "\\Leftarrow ", description: "" },
            { latex: "\\Rightarrow ", description: "" },
            { latex: "\\Leftrightarrow ", description: "" },
            { latex: "\\longleftarrow ", description: "" },
            { latex: "\\longrightarrow ", description: "" },
            { latex: "\\longleftrightarrow ", description: "" },
            { latex: "\\Longleftarrow ", description: "" },
            { latex: "\\Longrightarrow ", description: "" },
            { latex: "\\Longleftrightarrow ", description: "" },
            { latex: "\\uparrow ", description: "" },
            { latex: "\\downarrow ", description: "" },
            { latex: "\\updownarrow ", description: "" },
            { latex: "\\Uparrow ", description: "" },
            { latex: "\\Downarrow ", description: "" },
            { latex: "\\Updownarrow ", description: "" },
            { latex: "\\mapsto ", description: "" },
            { latex: "\\longmapsto ", description: "" },
            { latex: "\\hookleftarrow ", description: "" },
            { latex: "\\hookrightarrow ", description: "" },
            { latex: "\\leftharpoonup ", description: "" },
            { latex: "\\rightharpoonup ", description: "" },
            { latex: "\\leftharpoondown ", description: "" },
            { latex: "\\rightharpoondown ", description: "" },
            { latex: "\\rightleftharpoons ", description: "" },
            { latex: "\\leadsto ", description: "" },
        ],
    },
];