export const mathmlSymbols = [
    {
        category: "Huruf Yunani",
        symbols: [
            { mathml: "<mi>&alpha;</mi>", description: "(alpha)" },
            { mathml: "<mi>&beta;</mi>", description: "(beta)" },
            { mathml: "<mi>&gamma;</mi>", description: "(gamma)" },
            { mathml: "<mi>&Gamma;</mi>", description: "(Gamma)" },
            { mathml: "<mi>&delta;</mi>", description: "(delta)" },
            { mathml: "<mi>&Delta;</mi>", description: "(Delta)" },
            { mathml: "<mi>&epsilon;</mi>", description: "(epsilon)" },
            { mathml: "<mi>&varepsilon;</mi>", description: "(varepsilon)" },
            { mathml: "<mi>&zeta;</mi>", description: "(zeta)" },
            { mathml: "<mi>&eta;</mi>", description: "(eta)" },
            { mathml: "<mi>&theta;</mi>", description: "(theta)" },
            { mathml: "<mi>&vartheta;</mi>", description: "(vartheta)" },
            { mathml: "<mi>&Theta;</mi>", description: "(Theta)" },
            { mathml: "<mi>&iota;</mi>", description: "(iota)" },
            { mathml: "<mi>&kappa;</mi>", description: "(kappa)" },
            { mathml: "<mi>&lambda;</mi>", description: "(lambda)" },
            { mathml: "<mi>&Lambda;</mi>", description: "(Lambda)" },
            { mathml: "<mi>&mu;</mi>", description: "(mu)" },
            { mathml: "<mi>&nu;</mi>", description: "(nu)" },
            { mathml: "<mi>&xi;</mi>", description: "(xi)" },
            { mathml: "<mi>&Xi;</mi>", description: "(Xi)" },
            { mathml: "<mi>&pi;</mi>", description: "(pi)" },
            { mathml: "<mi>&Pi;</mi>", description: "(Pi)" },
            { mathml: "<mi>&rho;</mi>", description: "(rho)" },
            { mathml: "<mi>&varrho;</mi>", description: "(varrho)" },
            { mathml: "<mi>&sigma;</mi>", description: "(sigma)" },
            { mathml: "<mi>&Sigma;</mi>", description: "(Sigma)" },
            { mathml: "<mi>&tau;</mi>", description: "(tau)" },
            { mathml: "<mi>&upsilon;</mi>", description: "(upsilon)" },
            { mathml: "<mi>&Upsilon;</mi>", description: "(Upsilon)" },
            { mathml: "<mi>&phi;</mi>", description: "(phi)" },
            { mathml: "<mi>&varphi;</mi>", description: "(varphi)" },
            { mathml: "<mi>&Phi;</mi>", description: "(Phi)" },
            { mathml: "<mi>&chi;</mi>", description: "(chi)" },
            { mathml: "<mi>&psi;</mi>", description: "(psi)" },
            { mathml: "<mi>&Psi;</mi>", description: "(Psi)" },
            { mathml: "<mi>&omega;</mi>", description: "(omega)" },
            { mathml: "<mi>&Omega;</mi>", description: "(Omega)" },
        ],
    },
    {
        category: "Panah",
        symbols: [
            { mathml: "<mo>&leftarrow;</mo>", description: "" },
            { mathml: "<mo>&rightarrow;</mo>", description: "" },
            { mathml: "<mo>&leftrightarrow;</mo>", description: "" },
            { mathml: "<mo>&Leftarrow;</mo>", description: "" },
            { mathml: "<mo>&Rightarrow;</mo>", description: "" },
            { mathml: "<mo>&Leftrightarrow;</mo>", description: "" },
            { mathml: "<mo>&longleftarrow;</mo>", description: "" },
            { mathml: "<mo>&longrightarrow;</mo>", description: "" },
            { mathml: "<mo>&longleftrightarrow;</mo>", description: "" },
            { mathml: "<mo>&Longleftarrow;</mo>", description: "" },
            { mathml: "<mo>&Longrightarrow;</mo>", description: "" },
            { mathml: "<mo>&Longleftrightarrow;</mo>", description: "" },
            { mathml: "<mo>&uparrow;</mo>", description: "" },
            { mathml: "<mo>&downarrow;</mo>", description: "" },
            { mathml: "<mo>&updownarrow;</mo>", description: "" },
            { mathml: "<mo>&Uparrow;</mo>", description: "" },
            { mathml: "<mo>&Downarrow;</mo>", description: "" },
            { mathml: "<mo>&Updownarrow;</mo>", description: "" },
            { mathml: "<mo>&mapsto;</mo>", description: "" },
            { mathml: "<mo>&longmapsto;</mo>", description: "" },
            { mathml: "<mo>&hookleftarrow;</mo>", description: "" },
            { mathml: "<mo>&hookrightarrow;</mo>", description: "" },
            { mathml: "<mo>&leftharpoonup;</mo>", description: "" },
            { mathml: "<mo>&rightharpoonup;</mo>", description: "" },
            { mathml: "<mo>&leftharpoondown;</mo>", description: "" },
            { mathml: "<mo>&rightharpoondown;</mo>", description: "" },
            { mathml: "<mo>&rightleftharpoons;</mo>", description: "" },
            { mathml: "<mo>&leadsto;</mo>", description: "" },
        ],
    },
];

export const mathmlOperations = [
    {
        category: "small",
        symbols: [
            { mathml: "<mo>&times;</mo>" },
            { mathml: "<mo>&divide;</mo>" },
            { mathml: "<mo>&middot;</mo>" },
            { mathml: "<mo>&ne;</mo>" },
            { mathml: "<mover><mi>x</mi><mo>&macr;</mo></mover>" },
            { mathml: "<mover><mi>x</mi><mo>&rarr;</mo></mover>" },
            { mathml: "<mover><mi>x</mi><mo>&dot;</mo></mover>" },
            { mathml: "<mfrac><mi>a</mi><mi>b</mi></mfrac>" },
            { mathml: "<msup><mi>a</mi><mi>b</mi></msup>" },
            { mathml: "<msub><mi>a</mi><mi>b</mi></msub>" },
            { mathml: "<msubsup><mi>x</mi><mi>a</mi><mi>b</mi></msubsup>" },
            { mathml: "<msqrt><mi>x</mi></msqrt>" },
            { mathml: "<mroot><mi>x</mi><mi>n</mi></mroot>" },
            { mathml: "<mo>&int;</mo>" },
            { mathml: "<msubsup><mo>&int;</mo><mi>a</mi><mi>b</mi></msubsup>" },
            { mathml: "<msubsup><mo>&sum;</mo><mi>a</mi><mi>b</mi></msubsup>" },
        ],
    },
    {
        category: "long",
        symbols: [
            { mathml: "<munder><mo>lim</mo><mrow><mi>x</mi><mo>&rarr;</mo><mn>0</mn></mrow></munder>" },
            { mathml: "<msub><mo>log</mo><mi>a</mi></msub><mi>b</mi>" },
            { mathml: "<mo>sin</mo>" },
            { mathml: "<mo>cos</mo>" },
            { mathml: "<mo>tan</mo>" },
        ],
    },
    {
        category: "big",
        symbols: [
            { mathml: "<mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable>" },
            { mathml: "<mrow><mo>(</mo><mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable><mo>)</mo></mrow>" },
            { mathml: "<mrow><mo>[</mo><mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable><mo>]</mo></mrow>" },
            { mathml: "<mrow><mo>{</mo><mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable><mo>}</mo></mrow>" },
            { mathml: "<mrow><mo>|</mo><mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable><mo>|</mo></mrow>" },
        ],
    },
];